// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import HelloController from "./hello_controller"
application.register("hello", HelloController)
import MonthlyChartController from "./monthly_chart_controller"
application.register("monthly-chart", MonthlyChartController)
import DateRangeController from "./date_range_controller"
application.register("date-range", DateRangeController)